<a href="https://colab.research.google.com/github/devdandekar33/ML-/blob/ML-colab/Movie_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Content based Recommendation
2.Popularity based Recommendation
3.Collaborative Recommendation

In [ ]:
#movies dataset
#we are using Popularity based Recommendation

In [ ]:
#importing
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
#data collection
movies_data=pd.read_csv('/content/movies.csv')
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [ ]:
movies_data.shape

(4803, 24)

In [ ]:
#selecting the relevant features for recommendation
selected_features=['genres','keywords','original_language','cast','director']
print(selected_features)

['genres', 'keywords', 'original_language', 'cast', 'director']


In [ ]:
#replacing null values with null string
for feature in selected_features:
  movies_data[feature]=movies_data[feature].fillna('')

In [ ]:
#combining all selected features
combined_features=movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['original_language']+' '+movies_data['cast']+' '+movies_data['director']
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  en Edward Burns Kerry Bish\u00...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      en Daniel Henney Eliza Coupe Bill Paxton Ala...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [ ]:
#converting the text data to feature vectors
vectorizer=TfidfVectorizer()
feature_vectors=vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectors)

  (0, 2063)	0.18665186499447553
  (0, 6551)	0.12242341251354961
  (0, 11232)	0.209898604739424
  (0, 8840)	0.17353590912089956
  (0, 7505)	0.24540176320809437
  (0, 12584)	0.1637235952387991
  (0, 14312)	0.2144334213116376
  (0, 12150)	0.22256873370821878
  (0, 11506)	0.23530526953263461
  (0, 14843)	0.21826588105197828
  (0, 14582)	0.25549825688355415
  (0, 11533)	0.16260042698137087
  (0, 4168)	0.037343528466907444
  (0, 12316)	0.23530526953263461
  (0, 2758)	0.26972846547717394
  (0, 14256)	0.13883081597626545
  (0, 12403)	0.3766735943238939
  (0, 4893)	0.19824203143913924
  (0, 2618)	0.24259258332105782
  (0, 3119)	0.2311715546144746
  (0, 4573)	0.1121952263281294
  (0, 11761)	0.11206402612776617
  (0, 4442)	0.12012539827085399
  (0, 144)	0.09827307248858286
  (0, 86)	0.08502902364077554
  :	:
  (4801, 14819)	0.322455239802952
  (4801, 4102)	0.2761196091597497
  (4801, 253)	0.19806508189922148
  (4801, 5852)	0.322455239802952
  (4801, 10080)	0.24085559924078767
  (4801, 1384)	0.174

In [ ]:
#Cosine similarity for getting a similarity score
similarity=cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.02820855 0.04616569 ... 0.00128325 0.00152922 0.00127856]
 [0.02820855 1.         0.01627439 ... 0.01762654 0.00131869 0.00110253]
 [0.04616569 0.01627439 1.         ... 0.0013247  0.06723507 0.00131986]
 ...
 [0.00128325 0.01762654 0.0013247  ... 1.         0.00140718 0.0266944 ]
 [0.00152922 0.00131869 0.06723507 ... 0.00140718 1.         0.00140204]
 [0.00127856 0.00110253 0.00131986 ... 0.0266944  0.00140204 1.        ]]


In [ ]:
similarity.shape

(4803, 4803)

In [ ]:
#getting the movie name from user
movie_name=input("Enter your Favourite movie's name :")

Enter your Favourite movie's name :iron man


In [ ]:
#creating a list with all the movies given in the dataset
list_of_all_titles=movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [ ]:
#finding the close match for the movie name given by the user
find_close_match= difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [ ]:
close_match=find_close_match[0]
print(close_match)

Iron Man


IMPORTANT

In [ ]:
#finding the index of movie title
index_of_the_movie = movies_data[movies_data.title ==close_match]['index'].values[0]
print(index_of_the_movie)


68


In [ ]:
#getting a list of similar movies
similarity_score=list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.04259757918740533), (1, 0.0614530077393899), (2, 0.01851172019096729), (3, 0.009225150345286755), (4, 0.04294531628377375), (5, 0.017691386586349608), (6, 0.03691106285098383), (7, 0.28587352281916245), (8, 0.011176133856612196), (9, 0.09390978534248384), (10, 0.08564999527288482), (11, 0.017376030477728347), (12, 0.01746386311575862), (13, 0.01629723288066938), (14, 0.12080579638893466), (15, 0.009945897290292199), (16, 0.2828997471239597), (17, 0.017940463298414092), (18, 0.030589899986283857), (19, 0.06824416931933922), (20, 0.09738821423451778), (21, 0.017201076719952847), (22, 0.011425004062050131), (23, 0.01128049054287403), (24, 0.01679620464992332), (25, 0.0014367657314568393), (26, 0.265143328621221), (27, 0.03821960385979366), (28, 0.07498307662332873), (29, 0.01866386584150158), (30, 0.09753483725951585), (31, 0.3998658664025866), (32, 0.010478257484102702), (33, 0.15374796427543816), (34, 0.0014275121631221188), (35, 0.0429970876418771), (36, 0.04027058358589055), (3

In [ ]:
len(similarity_score)

4803

In [ ]:
#sorting the movies based on similarity score
sorted_similar_movies=sorted(similarity_score,key=lambda x:x[1], reverse=True)
print(sorted_similarity_movies)

[(68, 1.0), (79, 0.544293751661994), (31, 0.3998658664025866), (7, 0.28587352281916245), (16, 0.2828997471239597), (26, 0.265143328621221), (3623, 0.20150563807622968), (85, 0.2006881935698742), (511, 0.19999727061038167), (203, 0.19934487873162665), (182, 0.19649949647783213), (101, 0.1907765552807784), (64, 0.18704183297533739), (174, 0.1845636130881637), (2487, 0.175858859564058), (4401, 0.16813959822768226), (788, 0.16760284589997984), (1740, 0.16515180403922872), (126, 0.16382656103619964), (46, 0.16327423071746688), (1553, 0.15448414029283056), (33, 0.15374796427543816), (783, 0.14837264655708007), (2442, 0.1481307832340157), (2651, 0.14693350206800254), (138, 0.14583950702496623), (607, 0.13722577808098385), (38, 0.13498015928854948), (307, 0.1341562439238239), (122, 0.13361588022626159), (661, 0.13150719988920276), (1368, 0.128604812859313), (242, 0.12686681304059114), (2390, 0.1261595266893046), (2235, 0.12608436426173128), (720, 0.12485020937895239), (169, 0.12481834575042199

In [ ]:
#print the name of similar movies based on the index
print('Movies suggested for you  :\n ')
i=1
for movie in sorted_similar_movies:
  index=movie[0]
  title_from_index=movies_data[movies_data.index==index]['title'].values[0]
  if (i<=20):
    print(i,'.',title_from_index)
    i+=1

Movies suggested for you  :
 
1 . Iron Man
2 . Iron Man 2
3 . Iron Man 3
4 . Avengers: Age of Ultron
5 . The Avengers
6 . Captain America: Civil War
7 . Made
8 . Captain America: The Winter Soldier
9 . X-Men
10 . X2
11 . Ant-Man
12 . X-Men: First Class
13 . X-Men: Apocalypse
14 . The Incredible Hulk
15 . Duets
16 . The Helix... Loaded
17 . Deadpool
18 . Kick-Ass 2
19 . Thor: The Dark World
20 . X-Men: Days of Future Past


Movie recommendation system

In [ ]:
#getting the movie name from user
movie_name=input("Enter your Favourite movie's name :")
list_of_all_titles=movies_data['title'].tolist()
find_close_match= difflib.get_close_matches(movie_name,list_of_all_titles)
close_match=find_close_match[0]
index_of_the_movie = movies_data[movies_data.title ==close_match]['index'].values[0]
similarity_score=list(enumerate(similarity[index_of_the_movie]))
sorted_similar_movies=sorted(similarity_score,key=lambda x:x[1], reverse=True)
print('Movies suggested for you  :\n ')
i=1
for movie in sorted_similar_movies:
  index=movie[0]
  title_from_index=movies_data[movies_data.index==index]['title'].values[0]
  if (i<=20):
    print(i,'.',title_from_index)
    i+=1

Enter your Favourite movie's name :batman
Movies suggested for you  :
 
1 . Batman
2 . Batman Returns
3 . Batman & Robin
4 . The Dark Knight Rises
5 . Batman Begins
6 . The Dark Knight
7 . A History of Violence
8 . The Sentinel
9 . Superman
10 . Mars Attacks!
11 . Beetlejuice
12 . The Mask
13 . Man of Steel
14 . Jonah Hex
15 . Spider-Man 3
16 . Spider-Man 2
17 . Something's Gotta Give
18 . Superman III
19 . Blood and Wine
20 . Green Lantern
